export { apiCliente } from './api';
export * from './authServicio';
export * from './formulariosAdminServicio';
export * from './usuariosAdminServicio';
export * from './archivosServicio';
export * from './catalogosServicio';
export * from './formulariosServicio';
export * from './interfazServicio';
export * from './reglasServicio';
export * from './respuestasServicio';
export * from './sesionesServicio';
export * from './sincronizacionServicio';
export * from './internacionalizacionServicio';
export * from './saludServicio';
